name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update GitHub Stats
        uses: anuraghazra/github-readme-stats@v2 # Adjust version as needed
        with:
          username: yousufislam191
          token: ${{ secrets.GH_README_STATS_TOKEN }} # Use your secret name here
          enable_private: true # Ensure this is set to true to include private repository stats

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update GitHub Stats in README"
          git push
